version: '3.9'

services:
  guise:
    container_name: o3rd_persona
    build:
      context: ./persona
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
