version: '3.9'

services:
  guise:
    container_name: guise
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - guise_node:node_modules

volumes:
  guise_node:
